language: objective-c
matrix:
  include:
    - osx_image: xcode7.2
      env: TEST_SDK=macosx10.11 TEST_SCHEME="OS X"
    - osx_image: xcode7.2
      env: TEST_SDK=iphonesimulator9.2
    - osx_image: xcode7.1
      env: TEST_SDK=iphonesimulator9.1
    - osx_image: xcode6.4
      env: TEST_SDK=iphonesimulator8.4
    - osx_image: beta-xcode6.3
      env: TEST_SDK=iphonesimulator8.3
    - osx_image: beta-xcode6.2
      env: TEST_SDK=iphonesimulator8.2
    - env: TEST_SDK=macosx10.10 TEST_SCHEME="OS X"
    - env: TEST_SDK=macosx10.9 TEST_SCHEME="OS X"
    - env: TEST_SDK=iphonesimulator8.1
    - env: TEST_SDK=iphonesimulator7.1
    - env: TEST_SDK=iphonesimulator7.0
script: xctool -project HTMLReader.xcodeproj -scheme "HTMLReader ${TEST_SCHEME:-iOS}" -sdk $TEST_SDK ${TEST_ACTION:-test}
notifications:
  email:
    - nolan@nolanw.ca
